services:
  postgis:
    image: postgis/postgis:15-3.3
    container_name: postgis_br
    environment:
      POSTGRES_DB: address_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      # Armazenamento persistente no volume externo /Volumes/240
      - /Volumes/240/postgres_postgis_data:/var/lib/postgresql/data
      # Scripts SQL do repositório
      - ./sql:/sql:ro
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
