-- ==========================================================================
-- PostGIS address_standardizer: Brazilian Lexicon Dataset (br_lex)
-- Data Provenance: Derived from official Brazilian public open data (IBGE / OpenStreetMap)
-- License: Public Domain / Open Source (BSD/PostGIS License)
-- ==========================================================================

CREATE TABLE IF NOT EXISTS br_lex (
    id serial,
    seq integer,
    word text,
    stdword text,
    token integer, is_custom boolean NOT NULL DEFAULT true, CONSTRAINT pk_br_lex PRIMARY KEY(id)
);

-- Upgrade protection for custom entries
DELETE FROM br_lex WHERE is_custom = false;

-- Default is_custom to false for shipped entries
ALTER TABLE br_lex ALTER COLUMN is_custom SET DEFAULT false;

INSERT INTO br_lex (seq, word, stdword, token)
WITH t(seq,word,stdword,token) AS ( VALUES 
(1, '&', 'E', 13),
(1, ',', ',', 9),
(1, '-', '-', 9),
(1, '/', '/', 9),
(1, 'AL', 'ALAMEDA', 2),
(1, 'AL.', 'ALAMEDA', 2),
(1, 'ALAMEDA', 'ALAMEDA', 2),
(1, 'ALTO', 'ALTO', 2),
(1, 'AND', 'ANDAR', 19),
(1, 'ANDAR', 'ANDAR', 19),
(1, 'ANEL', 'ANEL VIARIO', 2),
(1, 'AP', 'APTO', 19),
(1, 'AP.', 'APTO', 19),
(1, 'APARTAMENTO', 'APTO', 19),
(1, 'APT', 'APTO', 19),
(1, 'APTO', 'APTO', 19),
(1, 'AV', 'AVENIDA', 2),
(1, 'AV.', 'AVENIDA', 2),
(1, 'AVENIDA', 'AVENIDA', 2),
(1, 'BALNEARIO', 'BALNEARIO', 2),
(1, 'BALNEÁRIO', 'BALNEARIO', 2),
(1, 'BC', 'BECO', 2),
(1, 'BC.', 'BECO', 2),
(1, 'BECO', 'BECO', 2),
(1, 'BL', 'BLOCO', 19),
(1, 'BL.', 'BLOCO', 19),
(1, 'BLOCO', 'BLOCO', 19),
(1, 'CALCADA', 'CALCADA', 2),
(1, 'CALÇADA', 'CALCADA', 2),
(1, 'CASA', 'CASA', 19),
(1, 'CENTRO', 'CENTRO', 22),
(1, 'CH', 'CHACARA', 2),
(1, 'CH.', 'CHACARA', 2),
(1, 'CHACARA', 'CHACARA', 2),
(1, 'CHÁCARA', 'CHACARA', 2),
(1, 'CJ', 'CJTO', 19),
(1, 'CJ.', 'CJTO', 19),
(1, 'CLN', 'COMERCIO LOCAL NORTE', 2),
(1, 'CLS', 'COMERCIO LOCAL SUL', 2),
(1, 'COB', 'COBERTURA', 19),
(1, 'COBERTURA', 'COBERTURA', 19),
(1, 'COLONIA', 'COLONIA', 2),
(1, 'COLÔNIA', 'COLONIA', 2),
(1, 'COND', 'CONDOMINIO', 2),
(1, 'COND.', 'CONDOMINIO', 2),
(1, 'CONDOMINIO', 'CONDOMINIO', 2),
(1, 'CONDOMÍNIO', 'CONDOMINIO', 2),
(1, 'CONJ', 'CJTO', 19),
(1, 'CONJUNTO', 'CJTO', 19),
(1, 'CONTORNO', 'CONTORNO', 2),
(1, 'CRN', 'COMERCIO RESIDENCIAL NORTE', 2),
(1, 'CRS', 'COMERCIO RESIDENCIAL SUL', 2),
(1, 'CS', 'CASA', 19),
(1, 'D', 'D', 7),
(1, 'D''', 'D', 7),
(1, 'DA', 'DA', 7),
(1, 'DAS', 'DAS', 7),
(1, 'DE', 'DE', 7),
(1, 'DO', 'DO', 7),
(1, 'DOS', 'DOS', 7),
(1, 'E', 'E', 7),
(1, 'EQN', 'ENTRE QUADRA NORTE', 2),
(1, 'EQS', 'ENTRE QUADRA SUL', 2),
(1, 'ESTR', 'ESTRADA', 2),
(1, 'ESTR.', 'ESTRADA', 2),
(1, 'ESTRADA', 'ESTRADA', 2),
(1, 'FAZ', 'FAZENDA', 2),
(1, 'FAZ.', 'FAZENDA', 2),
(1, 'FAZENDA', 'FAZENDA', 2),
(1, 'FDS', 'FUNDOS', 19),
(1, 'FRENTE', 'FRENTE', 19),
(1, 'FRT', 'FRENTE', 19),
(1, 'FUNDOS', 'FUNDOS', 19),
(1, 'GALP', 'GALPAO', 19),
(1, 'GALPAO', 'GALPAO', 19),
(1, 'GALPÃO', 'GALPAO', 19),
(1, 'GAR', 'GARAGEM', 19),
(1, 'GARAGEM', 'GARAGEM', 19),
(1, 'JARDIM', 'JARDIM', 2),
(1, 'JD', 'JARDIM', 2),
(1, 'JD.', 'JARDIM', 2),
(1, 'KM', 'KM', 20),
(1, 'L', 'LESTE', 22),
(1, 'LAD', 'LADEIRA', 2),
(1, 'LAD.', 'LADEIRA', 2),
(1, 'LADEIRA', 'LADEIRA', 2),
(1, 'LARGO', 'LARGO', 2),
(1, 'LESTE', 'LESTE', 22),
(1, 'LG', 'LARGO', 2),
(1, 'LG.', 'LARGO', 2),
(1, 'LJ', 'LOJA', 19),
(1, 'LJ.', 'LOJA', 19),
(1, 'LOJA', 'LOJA', 19),
(1, 'LOT', 'LOTEAMENTO', 2),
(1, 'LOTE', 'LOTE', 19),
(1, 'LOTEAMENTO', 'LOTEAMENTO', 2),
(1, 'LT', 'LOTE', 19),
(1, 'LT.', 'LOTE', 19),
(1, 'MARGINAL', 'MARGINAL', 2),
(1, 'MORRO', 'MORRO', 2),
(1, 'N', 'NORTE', 22),
(1, 'N.', 'NUMERO', 19),
(1, 'NE', 'NORDESTE', 22),
(1, 'NO', 'NUMERO', 19),
(1, 'NO', 'NOROESTE', 22),
(1, 'NORDESTE', 'NORDESTE', 22),
(1, 'NOROESTE', 'NOROESTE', 22),
(1, 'NORTE', 'NORTE', 22),
(1, 'NUM', 'NUMERO', 19),
(1, 'NUMERO', 'NUMERO', 19),
(1, 'NW', 'NOROESTE', 22),
(1, 'Nº', 'NUMERO', 19),
(1, 'NÚMERO', 'NUMERO', 19),
(1, 'O', 'OESTE', 22),
(1, 'OESTE', 'OESTE', 22),
(1, 'PARQUE', 'PARQUE', 2),
(1, 'PASSAGEM', 'PASSAGEM', 2),
(1, 'PASSARELA', 'PASSARELA', 2),
(1, 'PAV', 'PAVIMENTO', 19),
(1, 'PAVIMENTO', 'PAVIMENTO', 19),
(1, 'PC', 'PRACA', 2),
(1, 'PC.', 'PRACA', 2),
(1, 'PCA', 'PRACA', 2),
(1, 'PCA.', 'PRACA', 2),
(1, 'PONTE', 'PONTE', 2),
(1, 'PQ', 'PARQUE', 2),
(1, 'PQ.', 'PARQUE', 2),
(1, 'PRACA', 'PRACA', 2),
(1, 'PRAÇA', 'PRACA', 2),
(1, 'PSG', 'PASSAGEM', 2),
(1, 'PTE', 'PONTE', 2),
(1, 'PÇA', 'PRACA', 2),
(1, 'PÇA.', 'PRACA', 2),
(1, 'Q.', 'QUADRA', 2),
(1, 'QD', 'QUADRA', 2),
(1, 'QD.', 'QUADRA', 2),
(1, 'QUADRA', 'QUADRA', 2),
(1, 'QUILOMETRO', 'KM', 20),
(1, 'QUILÔMETRO', 'KM', 20),
(1, 'QUIOSQUE', 'QUIOSQUE', 19),
(1, 'R', 'RUA', 2),
(1, 'R.', 'RUA', 2),
(1, 'RAMPA', 'RAMPA', 2),
(1, 'RES', 'RESIDENCIAL', 2),
(1, 'RES.', 'RESIDENCIAL', 2),
(1, 'RESIDENCIAL', 'RESIDENCIAL', 2),
(1, 'ROD', 'RODOVIA', 6),
(1, 'ROD.', 'RODOVIA', 6),
(1, 'RODOVIA', 'RODOVIA', 6),
(1, 'RUA', 'RUA', 2),
(1, 'S', 'SUL', 22),
(1, 'S/N', 'S/N', 0),
(1, 'SALA', 'SALA', 19),
(1, 'SE', 'SUDESTE', 22),
(1, 'SEM NUMERO', 'S/N', 0),
(1, 'SEM NÚMERO', 'S/N', 0),
(1, 'SERVIDAO', 'SERVIDAO', 2),
(1, 'SERVIDÃO', 'SERVIDAO', 2),
(1, 'SETOR', 'SETOR', 2),
(1, 'SHIN', 'SETOR DE HABITACOES INDIVIDUAIS NORTE', 2),
(1, 'SHIS', 'SETOR DE HABITACOES INDIVIDUAIS SUL', 2),
(1, 'SITIO', 'SITIO', 2),
(1, 'SL', 'SALA', 19),
(1, 'SL.', 'SALA', 19),
(1, 'SLJ', 'SOBRELOJA', 19),
(1, 'SN', 'S/N', 0),
(1, 'SO', 'SUDOESTE', 22),
(1, 'SOB', 'SOBRADO', 19),
(1, 'SOBRADO', 'SOBRADO', 19),
(1, 'SOBRELOJA', 'SOBRELOJA', 19),
(1, 'SQN', 'SUPERQUADRA NORTE', 2),
(1, 'SQS', 'SUPERQUADRA SUL', 2),
(1, 'SRV', 'SERVIDAO', 2),
(1, 'SS', 'SUBSOLO', 19),
(1, 'ST', 'SETOR', 2),
(1, 'ST.', 'SETOR', 2),
(1, 'SUBSOLO', 'SUBSOLO', 19),
(1, 'SUDESTE', 'SUDESTE', 22),
(1, 'SUDOESTE', 'SUDOESTE', 22),
(1, 'SUL', 'SUL', 22),
(1, 'SUPERQUADRA', 'SUPERQUADRA', 2),
(1, 'SW', 'SUDOESTE', 22),
(1, 'SÍTIO', 'SITIO', 2),
(1, 'TR', 'TRECHO', 2),
(1, 'TRAV', 'TRAVESSA', 2),
(1, 'TRAVESSA', 'TRAVESSA', 2),
(1, 'TRECHO', 'TRECHO', 2),
(1, 'TREVO', 'TREVO', 2),
(1, 'TRV', 'TREVO', 2),
(1, 'TV', 'TRAVESSA', 2),
(1, 'TV.', 'TRAVESSA', 2),
(1, 'VD', 'VIADUTO', 2),
(1, 'VIA', 'VIA', 2),
(1, 'VIADUTO', 'VIADUTO', 2),
(1, 'VIELA', 'VIELA', 2),
(1, 'VILA', 'VILA', 2),
(1, 'VL', 'VILA', 2),
(1, 'VL.', 'VILA', 2)
)
SELECT seq, word, stdword, token FROM t;
