-- ==========================================================================
-- PostGIS address_standardizer: Brazilian Lexicon Dataset (br_lex)
-- Data Provenance: Derived from public open sources (IBGE official open data and OpenStreetMap)
-- OpenStreetMap data is (c) OpenStreetMap contributors, licensed under the Open Data Commons Open Database License (ODbL) (https://opendatacommons.org/licenses/odbl/)
-- License: BSD/PostGIS License & Open Database License (ODbL) for OSM-derived terminology
-- ==========================================================================

CREATE TABLE IF NOT EXISTS br_lex (
    id serial,
    seq integer,
    word text,
    stdword text,
    token integer, is_custom boolean NOT NULL DEFAULT true, CONSTRAINT pk_br_lex PRIMARY KEY(id)
);

-- Upgrade protection for custom entries
DELETE FROM br_lex WHERE is_custom = false;

-- Default is_custom to false for shipped entries
ALTER TABLE br_lex ALTER COLUMN is_custom SET DEFAULT false;

INSERT INTO br_lex (seq, word, stdword, token)
WITH t(seq,word,stdword,token) AS ( VALUES 
(1, '&', 'E', 13),
(1, ',', ',', 9),
(1, '-', '-', 9),
(1, '/', '/', 9),
(1, '25 DE', '25 DE', 1),
(1, '9 DE', '9 DE', 1),
(1, 'AC', 'AC', 1),
(2, 'AC', 'AC', 6),
(1, 'AL', 'AL', 1),
(2, 'AL', 'AL', 6),
(3, 'AL', 'ALAMEDA', 2),
(1, 'AL.', 'ALAMEDA', 2),
(1, 'ALAMEDA', 'ALAMEDA', 2),
(1, 'ALTO', 'ALTO', 2),
(1, 'AM', 'AM', 1),
(2, 'AM', 'AM', 6),
(1, 'AND', 'ANDAR', 19),
(1, 'ANDAR', 'ANDAR', 19),
(1, 'ANEL', 'ANEL VIARIO', 2),
(1, 'AP', 'AP', 1),
(2, 'AP', 'AP', 6),
(3, 'AP', 'APTO', 19),
(1, 'AP.', 'APTO', 19),
(1, 'APARTAMENTO', 'APTO', 19),
(1, 'APT', 'APTO', 19),
(1, 'APTO', 'APTO', 19),
(1, 'AV', 'AVENIDA', 2),
(1, 'AV.', 'AVENIDA', 2),
(1, 'AVENIDA', 'AVENIDA', 2),
(1, 'BA', 'BA', 1),
(2, 'BA', 'BA', 6),
(1, 'BALNEARIO', 'BALNEARIO', 2),
(1, 'BALNEÁRIO', 'BALNEARIO', 2),
(1, 'BC', 'BECO', 2),
(1, 'BC.', 'BECO', 2),
(1, 'BECO', 'BECO', 2),
(1, 'BL', 'BLOCO', 19),
(1, 'BL.', 'BLOCO', 19),
(1, 'BLOCO', 'BLOCO', 19),
(1, 'BR', 'BR', 1),
(2, 'BR', 'BR', 6),
(1, 'CALCADA', 'CALCADA', 2),
(1, 'CALÇADA', 'CALCADA', 2),
(1, 'CASA', 'CASA', 1),
(2, 'CASA', 'CASA', 19),
(1, 'CE', 'CE', 1),
(2, 'CE', 'CE', 6),
(1, 'CENTRO', 'CENTRO', 22),
(1, 'CH', 'CHACARA', 2),
(1, 'CH.', 'CHACARA', 2),
(1, 'CHACARA', 'CHACARA', 2),
(1, 'CHÁCARA', 'CHACARA', 2),
(1, 'CJ', 'CJTO', 19),
(1, 'CJ.', 'CJTO', 19),
(1, 'CLN', 'COMERCIO LOCAL NORTE', 2),
(1, 'CLS', 'COMERCIO LOCAL SUL', 2),
(1, 'COB', 'COBERTURA', 19),
(1, 'COBERTURA', 'COBERTURA', 19),
(1, 'COLONIA', 'COLONIA', 2),
(1, 'COLÔNIA', 'COLONIA', 2),
(1, 'COND', 'CONDOMINIO', 2),
(1, 'COND.', 'CONDOMINIO', 2),
(1, 'CONDOMINIO', 'CONDOMINIO', 2),
(1, 'CONDOMÍNIO', 'CONDOMINIO', 2),
(1, 'CONJ', 'CJTO', 19),
(1, 'CONJUNTO', 'CJTO', 19),
(1, 'CONTORNO', 'CONTORNO', 2),
(1, 'CRN', 'COMERCIO RESIDENCIAL NORTE', 2),
(1, 'CRS', 'COMERCIO RESIDENCIAL SUL', 2),
(1, 'CS', 'CASA', 19),
(1, 'D', 'D', 7),
(1, 'D''', 'D', 7),
(1, 'DA', 'DA', 7),
(1, 'DAS', 'DAS', 7),
(1, 'DE', 'DE', 7),
(1, 'DF', 'DF', 1),
(2, 'DF', 'DF', 6),
(1, 'DO', 'DO', 7),
(1, 'DOS', 'DOS', 7),
(1, 'E', 'E', 7),
(1, 'EQN', 'ENTRE QUADRA NORTE', 2),
(1, 'EQS', 'ENTRE QUADRA SUL', 2),
(1, 'ES', 'ES', 1),
(2, 'ES', 'ES', 6),
(1, 'ESTR', 'ESTRADA', 2),
(1, 'ESTR.', 'ESTRADA', 2),
(1, 'ESTRADA', 'ESTRADA', 2),
(1, 'FAZ', 'FAZENDA', 2),
(1, 'FAZ.', 'FAZENDA', 2),
(1, 'FAZENDA', 'FAZENDA', 2),
(1, 'FDS', 'FUNDOS', 16),
(1, 'FRENTE', 'FRENTE', 16),
(1, 'FRT', 'FRENTE', 16),
(1, 'FUNDOS', 'FUNDOS', 16),
(1, 'GALP', 'GALPAO', 19),
(1, 'GALPAO', 'GALPAO', 19),
(1, 'GALPÃO', 'GALPAO', 19),
(1, 'GAR', 'GARAGEM', 19),
(1, 'GARAGEM', 'GARAGEM', 19),
(1, 'GO', 'GO', 1),
(2, 'GO', 'GO', 6),
(1, 'JARDIM', 'JARDIM', 2),
(1, 'JD', 'JARDIM', 2),
(1, 'JD.', 'JARDIM', 2),
(1, 'KM', 'KM', 20),
(1, 'L', 'LESTE', 22),
(1, 'LAD', 'LADEIRA', 2),
(1, 'LAD.', 'LADEIRA', 2),
(1, 'LADEIRA', 'LADEIRA', 2),
(1, 'LARGO', 'LARGO', 2),
(1, 'LESTE', 'LESTE', 22),
(1, 'LG', 'LARGO', 2),
(1, 'LG.', 'LARGO', 2),
(1, 'LJ', 'LOJA', 19),
(1, 'LJ.', 'LOJA', 19),
(1, 'LOJA', 'LOJA', 19),
(1, 'LOT', 'LOTEAMENTO', 2),
(1, 'LOTE', 'LOTE', 19),
(1, 'LOTEAMENTO', 'LOTEAMENTO', 2),
(1, 'LT', 'LOTE', 19),
(1, 'LT.', 'LOTE', 19),
(1, 'MA', 'MA', 1),
(2, 'MA', 'MA', 6),
(1, 'MARGINAL', 'MARGINAL', 2),
(1, 'MG', 'MG', 1),
(2, 'MG', 'MG', 6),
(1, 'MORRO', 'MORRO', 2),
(1, 'MS', 'MS', 1),
(2, 'MS', 'MS', 6),
(1, 'MT', 'MT', 1),
(2, 'MT', 'MT', 6),
(1, 'N', '', 19),
(2, 'N', 'NORTE', 22),
(1, 'N.', '', 19),
(1, 'NE', 'NORDESTE', 22),
(1, 'NO', '', 19),
(2, 'NO', 'NOROESTE', 22),
(1, 'NORDESTE', 'NORDESTE', 22),
(1, 'NOROESTE', 'NOROESTE', 22),
(1, 'NORTE', 'NORTE', 22),
(1, 'NUM', '', 19),
(1, 'NUMERO', '', 19),
(1, 'NW', 'NOROESTE', 22),
(1, 'Nº', '', 19),
(1, 'NÚMERO', '', 19),
(1, 'O', 'OESTE', 22),
(1, 'OESTE', 'OESTE', 22),
(1, 'PA', 'PA', 1),
(2, 'PA', 'PA', 6),
(1, 'PARQUE', 'PARQUE', 2),
(1, 'PASSAGEM', 'PASSAGEM', 2),
(1, 'PASSARELA', 'PASSARELA', 2),
(1, 'PAV', 'PAVIMENTO', 19),
(1, 'PAVIMENTO', 'PAVIMENTO', 19),
(1, 'PB', 'PB', 1),
(2, 'PB', 'PB', 6),
(1, 'PC', 'PRACA', 2),
(1, 'PC.', 'PRACA', 2),
(1, 'PCA', 'PRACA', 2),
(1, 'PCA.', 'PRACA', 2),
(1, 'PE', 'PE', 1),
(2, 'PE', 'PE', 6),
(1, 'PI', 'PI', 1),
(2, 'PI', 'PI', 6),
(1, 'PONTE', 'PONTE', 2),
(1, 'PQ', 'PARQUE', 2),
(1, 'PQ.', 'PARQUE', 2),
(1, 'PR', 'PR', 1),
(2, 'PR', 'PR', 6),
(1, 'PRACA', 'PRACA', 2),
(1, 'PRAÇA', 'PRACA', 2),
(1, 'PSG', 'PASSAGEM', 2),
(1, 'PTE', 'PONTE', 2),
(1, 'PÇA', 'PRACA', 2),
(1, 'PÇA.', 'PRACA', 2),
(1, 'Q.', 'QUADRA', 2),
(1, 'QD', 'QUADRA', 2),
(1, 'QD.', 'QUADRA', 2),
(1, 'QUADRA', 'QUADRA', 2),
(1, 'QUILOMETRO', 'KM', 20),
(1, 'QUILÔMETRO', 'KM', 20),
(1, 'QUIOSQUE', 'QUIOSQUE', 19),
(1, 'R', 'RUA', 2),
(1, 'R.', 'RUA', 2),
(1, 'RAMPA', 'RAMPA', 2),
(1, 'RES', 'RESIDENCIAL', 2),
(1, 'RES.', 'RESIDENCIAL', 2),
(1, 'RESIDENCIAL', 'RESIDENCIAL', 2),
(1, 'RJ', 'RJ', 1),
(2, 'RJ', 'RJ', 6),
(1, 'RN', 'RN', 1),
(2, 'RN', 'RN', 6),
(1, 'RO', 'RO', 1),
(2, 'RO', 'RO', 6),
(1, 'ROD', 'RODOVIA', 6),
(1, 'ROD.', 'RODOVIA', 6),
(1, 'RODOVIA', 'RODOVIA', 6),
(1, 'RR', 'RR', 1),
(2, 'RR', 'RR', 6),
(1, 'RS', 'RS', 1),
(2, 'RS', 'RS', 6),
(1, 'RUA', 'RUA', 2),
(1, 'S', 'SUL', 22),
(1, 'S/N', 'S/N', 0),
(1, 'SALA', 'SALA', 19),
(1, 'SC', 'SC', 1),
(2, 'SC', 'SC', 6),
(1, 'SE', 'SE', 1),
(2, 'SE', 'SE', 6),
(3, 'SE', 'SUDESTE', 22),
(1, 'SEM NUMERO', 'S/N', 0),
(1, 'SEM NÚMERO', 'S/N', 0),
(1, 'SERVIDAO', 'SERVIDAO', 2),
(1, 'SERVIDÃO', 'SERVIDAO', 2),
(1, 'SETOR', 'SETOR', 2),
(1, 'SHIN', 'SETOR DE HABITACOES INDIVIDUAIS NORTE', 2),
(1, 'SHIS', 'SETOR DE HABITACOES INDIVIDUAIS SUL', 2),
(1, 'SITIO', 'SITIO', 2),
(1, 'SL', 'SALA', 19),
(1, 'SL.', 'SALA', 19),
(1, 'SLJ', 'SOBRELOJA', 19),
(1, 'SN', 'S/N', 0),
(1, 'SO', 'SUDOESTE', 22),
(1, 'SOB', 'SOBRADO', 19),
(1, 'SOBRADO', 'SOBRADO', 19),
(1, 'SOBRELOJA', 'SOBRELOJA', 19),
(1, 'SP', 'SP', 1),
(2, 'SP', 'SP', 6),
(1, 'SQN', 'SUPERQUADRA NORTE', 2),
(1, 'SQS', 'SUPERQUADRA SUL', 2),
(1, 'SRV', 'SERVIDAO', 2),
(1, 'SS', 'SUBSOLO', 19),
(1, 'ST', 'SETOR', 2),
(1, 'ST.', 'SETOR', 2),
(1, 'SUBSOLO', 'SUBSOLO', 19),
(1, 'SUDESTE', 'SUDESTE', 22),
(1, 'SUDOESTE', 'SUDOESTE', 22),
(1, 'SUL', 'SUL', 22),
(1, 'SUPERQUADRA', 'SUPERQUADRA', 2),
(1, 'SW', 'SUDOESTE', 22),
(1, 'SÍTIO', 'SITIO', 2),
(1, 'TO', 'TO', 1),
(2, 'TO', 'TO', 6),
(1, 'TR', 'TRECHO', 2),
(1, 'TRAV', 'TRAVESSA', 2),
(1, 'TRAVESSA', 'TRAVESSA', 2),
(1, 'TRECHO', 'TRECHO', 2),
(1, 'TREVO', 'TREVO', 2),
(1, 'TRV', 'TREVO', 2),
(1, 'TV', 'TRAVESSA', 2),
(1, 'TV.', 'TRAVESSA', 2),
(1, 'VD', 'VIADUTO', 2),
(1, 'VIA', 'VIA', 2),
(1, 'VIADUTO', 'VIADUTO', 2),
(1, 'VIELA', 'VIELA', 2),
(1, 'VILA', 'VILA', 2),
(1, 'VL', 'VILA', 2),
(1, 'VL.', 'VILA', 2)
)
SELECT seq, word, stdword, token FROM t;

-- Reset default back to custom so new user entries won't be purged on upgrade
ALTER TABLE br_lex ALTER COLUMN is_custom SET DEFAULT true;
